"""Register of the passages left out of the translation → OMISSIONS.md (project root).

Usage: scriptorium run omissions_report

The `{{omitted: …}}` markers are the source of truth (CONVENTIONS.md, "Omitted passages"):
this collects them from every transcribed page (source/pages/NNNN/de.md), with the section
they sit in, so the register can't drift from the text. Notes containing "(borderline)" are
listed separately for a human decision.
"""
import re
from pathlib import Path

import yaml

from bookroot import ROOT  # the book project (book.yaml), not the kit
MARKER = re.compile(r'\{\{omitted:\s*(\w+)\s*\|\s*pages:\s*([^|]+?)\s*\|\s*note:\s*"(.*?)"\s*\}\}')
HEADING = re.compile(r"^#+\s+(.*)$", re.M)


def unit_of(page: int, units: list[dict]) -> str:
    for u in units:
        if any(a <= page <= b for a, b in u.get("ranges") or [[u["first"], u["last"]]]):
            return u.get("title_en") or u["slug"]
    return "?"


def main() -> None:
    units = yaml.safe_load((ROOT / "source" / "units.yaml").read_text())
    rows, section = [], ""
    for page_dir in sorted((ROOT / "source" / "pages").iterdir()):
        de = page_dir / "de.md"
        if not page_dir.name.isdigit() or not de.exists():
            continue
        text = de.read_text()
        # Track the current section across pages: the last heading before each marker.
        pos = 0
        for m in MARKER.finditer(text):
            heads = HEADING.findall(text[pos:m.start()])
            if heads:
                section = heads[-1]
            pos = m.end()
            rows.append({"page": int(page_dir.name), "kind": m.group(1), "pages": m.group(2),
                         "note": m.group(3), "section": section, "unit": unit_of(int(page_dir.name), units)})
        heads = HEADING.findall(text[pos:])
        if heads:
            section = heads[-1]

    # A marker repeated on consecutive page files for one passage counts once.
    seen, unique = set(), []
    for r in rows:
        key = (r["pages"], r["note"])
        if key not in seen:
            seen.add(key)
            unique.append(r)

    def pages_in(spec: str) -> set[int]:
        """"512–513" → {512, 513}; "140" → {140}."""
        nums = [int(n) for n in re.findall(r"\d+", spec)]
        return set(range(nums[0], nums[-1] + 1)) if nums else set()

    touched = set().union(*(pages_in(r["pages"]) for r in unique)) if unique else set()

    lines = ["# Passages not included in the translation", "",
             "Generated by `scriptorium run omissions_report` from the `{{omitted: …}}` markers in the transcribed pages —",
             "don't edit by hand. Rule: `CONVENTIONS.md`, \"Omitted passages: chemical synthesis\" (from chapter 6 onward).", "",
             f"**{len(unique)} passages** on **{len(touched)} printed pages** (pages touched; most are only partly omitted).", "",
             "| Unit | Section | Pages | What is left out |", "|---|---|---|---|"]
    for r in unique:
        lines.append(f"| {r['unit']} | {r['section']} | {r['pages']} | {r['note']} |")
    borderline = [r for r in unique if "borderline" in r["note"].lower()]
    lines += ["", "## Borderline — for a human decision", ""]
    lines += [f"- pp. {r['pages']} ({r['section']}): {r['note']}" for r in borderline] or ["None."]
    lines += ["", "## Translated before the rule existed", "",
              "Units finished before 2026-09-27 (front matter, introduction, chapters 1–5 and the excursuses on natural",
              "products, fluorine, antidepressants, amine oxidases and bioisosterism) were translated in full; by decision",
              "of 2026-09-27 the rule is not applied to them for now, so they contain no omissions.", ""]
    (ROOT / "OMISSIONS.md").write_text("\n".join(lines) + "\n")
    print(f"{len(unique)} omitted passages → OMISSIONS.md")


if __name__ == "__main__":
    main()
